### add book
POST http://localhost:8000/api/create-book
Content-Type: application/json

  {
    "title": "To Us",
    "author": "Tiffany Nyawira",
    "year": 2022
  }

### update
### add book
PUT http://localhost:8000/api/update-book/1
Content-Type: application/json

  {
    "title": "To Us",
    "author": "Tiffany Nyawira",
    "year": 2022
  }


###
GET http://localhost:8000/api/books

###
GET https://bookmanagementbackend-dqh7avfsd0hgg6dz.canadacentral-01.azurewebsites.net/books


###
GET http://localhost:8000/api/books